project:
  type: website

website:
  title: "My awesome website"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
      - auto: "*.qmd"
      - tools:
        - icon: github
          href: https://github.com/smart-edtech/template/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



